language: android

jdk: oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-24

licenses:
 - android-sdk-preview-license-.+
 - android-sdk-license-.+
 - google-gdk-license-.+

script:
 - "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
