language: android

jdk: oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.0
  - android-24

licenses:
  - '.+'

script:
 - "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
